{% set name = "sql-language-server" %}
{% set version = "1.7.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://registry.npmjs.org/{{ name }}/-/{{ name }}-{{ version }}.tgz
  sha256: c66e8d94863c52c34cab0865be3bac61f152e8029ba32d95778d984c8e0a49b1

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - {{ stdlib('c') }}
    - make
    - nodejs
    - pnpm
    - pnpm-licenses
    - python
  run:
    - nodejs

test:
  commands:
    - {{ name }} --help

about:
  home: https://github.com/joe-re/{{ name }}
  license: MIT
  license_file:
    - LICENSE
    - third-party-licenses.txt
  summary: SQL Language Server
  dev_url: https://github.com/joe-re/{{ name }}

extra:
  recipe-maintainers:
    - danielnachun
